project_id = "ksrkowssinstecwyijom"

[functions.auth-handler]
verify_jwt = false

[functions.daily-goals]
verify_jwt = false

[functions.weekly-goals]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.fetch-reports]
verify_jwt = false
